[package]
name = "transfery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.5.1", default-features = false, features = ["macros"] }
lazy_static = { version = "1.4.0", default-features = false }
minio = { version = "0.1.0", default-features = false }
pico-args = { version = "0.5.0", default-features = false, features = ["short-space-opt"] }
sqlx = { version = "0.7.4", default-features = false, features = ["runtime-tokio", "mysql"] }
