version: '3'
services:
  transfery:
    container_name: transfery
    image: hlf01/transfery
    ports:
      - ${LOCAL_PORT}:8080
    restart: on-failure
    env_file:
      - .env
    command: pipenv run sanic run.app -H 0.0.0.0 -p 8080
